# Generated by Django 3.0.4 on 2020-03-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='olusturma_tarihi',
            new_name='olusturma_Tarihi',
        ),
    ]
