# Generated by Django 3.0.4 on 2020-05-24 13:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_auto_20200326_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='makale_resim',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Fotoğraf ekleyin'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='İçerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
