# Generated by Django 3.0.4 on 2020-05-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0004_auto_20200524_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='makale_resim',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
