# Generated by Django 3.0.4 on 2020-05-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0005_auto_20200525_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='makale_resim',
            new_name='makal_resim',
        ),
    ]
