# Generated by Django 3.0.4 on 2020-05-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_auto_20200525_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_yapan', models.CharField(max_length=50, verbose_name='isim')),
                ('yorum_içerik', models.CharField(max_length=200, verbose_name='yorum')),
                ('yorum_tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='makale.Makale', verbose_name='Makale')),
            ],
        ),
    ]
