# Generated by Django 3.0.6 on 2020-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0008_auto_20200527_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='yorum_içerik',
            field=models.CharField(max_length=200, verbose_name='yorum'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yorum_yapan',
            field=models.CharField(max_length=50, verbose_name='isim'),
        ),
    ]
