# Generated by Django 3.0.6 on 2020-05-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_auto_20200527_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yorum',
        ),
    ]
