# Generated by Django 3.0.6 on 2020-05-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makale', '0010_delete_yorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_yapan', models.CharField(max_length=50, verbose_name='isim')),
                ('yorum_içerik', models.CharField(max_length=200, verbose_name='yorum')),
                ('yorum_tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='makale.Makale', verbose_name='Makale')),
            ],
            options={
                'ordering': ['-yorum_tarih', 'yorum_yapan'],
            },
        ),
    ]
